spring:
  profiles:
    active: prod
  main:
    keep-alive: true
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: ${dbAddress}
    username: ${dbUsername}
    password: ${dbPassword}
    driverClassName: org.postgresql.Driver
avalon:
  exit:
    strategy: LOG
discord:
  token: ${discordToken}